#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

index='.just/units.just'
staged_index="$index.staged"

{
    echo '# GENERATED by .just/units.sh. Do not edit. Do not commit.'
    for unit_justfile in apps/*/Justfile libs/*/Justfile; do
        [ -e "$unit_justfile" ] || continue
        unit_dir="${unit_justfile%/Justfile}"
        unit_name="${unit_dir##*/}"
        path_from_index="../$unit_dir"
        echo "mod? $unit_name '$path_from_index'"
    done
} >"$staged_index"

mv "$staged_index" "$index"
