#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

verbs=(build test start)
unit_tasks="$(moon query tasks | jaq -r '.tasks | to_entries[] | .key as $unit | .value | keys[] | "\($unit) \(.)"')"

for verb in "${verbs[@]}"; do
    index=".just/$verb/units.just"
    staged_index="$index.staged"
    {
        echo '# GENERATED by .just/units.sh. Do not edit. Do not commit.'
        while read -r unit task; do
            [ "$task" = "$verb" ] || continue
            printf '\n%s *FLAGS:\n    moon run %s:%s {{FLAGS}}\n' "$unit" "$unit" "$verb"
        done <<<"$unit_tasks"
    } >"$staged_index"
    mv "$staged_index" "$index"
done
