set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Lint and type-check everything
all *FLAGS:
    moon run :lint {{FLAGS}}

# Lint and type-check one unit
unit UNIT *FLAGS:
    moon run {{UNIT}}:lint {{FLAGS}}
