set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Lint Markdown files
markdown:
    rumdl check .

# Lint every unit
units:
    moon run :lint

# Type-check every unit
types:
    moon run :typecheck

# Run every linter
all: markdown units types
