set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Test every unit
all:
    moon run :test

# Test one unit
unit UNIT:
    moon run {{UNIT}}:test

# Test only units affected by the current changes
affected:
    moon run :test --affected
