set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Test everything
all *FLAGS:
    moon run :test {{FLAGS}}

# Test one unit
unit UNIT *FLAGS:
    moon run {{UNIT}}:test {{FLAGS}}
