$schema: 'https://moonrepo.dev/schemas/v2/tasks.json'

inheritedBy:
  tags: ['nuxt']

tasks:
  lint:
    script: 'pnpm exec biome check . && pnpm exec nuxt typecheck'
    toolchains: 'system'
    deps:
      - 'repo:install'
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
      - '@globs(configs)'

  build:
    command: 'pnpm exec nuxt build'
    toolchains: 'system'
    deps:
      - 'repo:install'
    inputs:
      - '@globs(sources)'
      - '@globs(configs)'
    outputs:
      - '.output'

  start:
    command: 'pnpm exec nuxt dev'
    toolchains: 'system'
    deps:
      - 'repo:install'
    options:
      cache: false
      persistent: true
