set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Format Nix files
nix:
    alejandra .

# Format Markdown files
markdown:
    rumdl check --fix .

# Format every unit
units:
    moon run :format

# Run every formatter
all: nix markdown units
