set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Format everything
all *FLAGS:
    moon run :format {{FLAGS}}

# Format one unit
unit UNIT *FLAGS:
    moon run {{UNIT}}:format {{FLAGS}}
